"""App launcher — create .app bundles in ~/Applications."""

import os, sys, subprocess, shutil, plistlib
from pathlib import Path
from . import VERSION


def get_app_version(app_type="full"):
    """Read the version from an existing .app's Info.plist, or None."""
    app_name = "MacStressMonitor" if app_type == "full" else "MacStressMonitor Lite"
    app_path = Path.home() / "Applications" / f"{app_name}.app"
    plist_path = app_path / "Contents" / "Info.plist"
    if not plist_path.exists():
        return None
    try:
        with open(plist_path, "rb") as f:
            data = plistlib.load(f)
        return data.get("CFBundleShortVersionString")
    except Exception:
        return None


def ensure_app_bundle():
    """Create or update .app bundle if version changed or structure outdated."""
    current = get_app_version("full")
    needs_rebuild = current != VERSION

    # Also check if existing .app has LSUIElement (background mode)
    if not needs_rebuild and current:
        app_path = Path.home() / "Applications" / "MacStressMonitor.app"
        plist_path = app_path / "Contents" / "Info.plist"
        try:
            with open(plist_path, "rb") as f:
                data = plistlib.load(f)
            if "LSUIElement" not in data:
                needs_rebuild = True
        except Exception:
            needs_rebuild = True

    if not needs_rebuild:
        return  # Already up to date
    try:
        create_app_launcher("full", add_to_dock=False)
        print(f"  📦 .app bundle {'updated' if current else 'created'}: v{VERSION}")
    except Exception as e:
        print(f"  ⚠ Could not create .app: {e}")


def create_app_launcher(app_type="full", add_to_dock=False):
    """Create .app bundle in ~/Applications for easy launching."""
    apps_dir = Path.home() / "Applications"
    apps_dir.mkdir(exist_ok=True)

    if app_type == "full":
        app_name = "MacStressMonitor"
        python_path = sys.executable
        pkg_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        # Background launch — no Terminal window
        launch_cmd = f'cd "{pkg_dir}" && exec "{python_path}" -m macstress "$@"'
    else:
        app_name = "MacStressMonitor Lite"
        pkg_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        script_path = os.path.join(pkg_dir, "macstress_lite.sh")
        launch_cmd = f'exec bash "{script_path}"'

    app_path = apps_dir / f"{app_name}.app"

    if app_path.exists():
        shutil.rmtree(str(app_path), ignore_errors=True)

    contents = app_path / "Contents"
    macos = contents / "MacOS"
    macos.mkdir(parents=True, exist_ok=True)

    # Launcher script — runs backgrounded, no Terminal window
    launcher = macos / app_name.replace(" ", "")
    launcher.write_text(f"""#!/bin/bash
# {app_name} Launcher — auto-generated by MacStressMonitor v{VERSION}
# Runs the app in background without Terminal

LOG="$HOME/Library/Logs/MacStressMonitor.log"

# Kill any existing instance on port 9630
lsof -ti:9630 | xargs kill -9 2>/dev/null
sleep 0.3

# Run backgrounded
{launch_cmd} >> "$LOG" 2>&1 &
disown
""")
    launcher.chmod(0o755)

    resources = contents / "Resources"
    resources.mkdir(exist_ok=True)
    icon_dir = Path(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))) / "icons"
    icon_name = "macstress" if app_type == "full" else "macstress_lite"
    icon_src = icon_dir / f"{icon_name}.icns"
    icon_ref = ""
    if icon_src.exists():
        shutil.copy2(str(icon_src), str(resources / f"{icon_name}.icns"))
        icon_ref = f"\n    <key>CFBundleIconFile</key>\n    <string>{icon_name}</string>"

    plist = contents / "Info.plist"
    bundle_id = f"com.macstress.{app_name.lower().replace(' ', '')}"
    plist.write_text(f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>{app_name.replace(' ', '')}</string>
    <key>CFBundleIdentifier</key>
    <string>{bundle_id}</string>
    <key>CFBundleName</key>
    <string>{app_name}</string>
    <key>CFBundleVersion</key>
    <string>{VERSION}</string>
    <key>CFBundleShortVersionString</key>
    <string>{VERSION}</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>LSUIElement</key>
    <true/>{icon_ref}
</dict>
</plist>
""")

    # Register with LaunchServices
    lsreg = "/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister"
    subprocess.run([lsreg, "-f", str(app_path)], capture_output=True)

    # Add to Dock if requested
    if add_to_dock:
        _add_to_dock(str(app_path))

    print(f"  ✅ {app_name}.app створено в ~/Applications/")
    print(f"  📂 {app_path}")
    return str(app_path)


def _add_to_dock(app_path):
    """Add an app to the macOS Dock persistent-apps."""
    try:
        dock_plist = Path.home() / "Library" / "Preferences" / "com.apple.dock.plist"
        with open(dock_plist, "rb") as f:
            dock = plistlib.load(f)

        persistent = dock.get("persistent-apps", [])

        # Check if already in Dock
        for item in persistent:
            td = item.get("tile-data", {})
            fd = td.get("file-data", {})
            if fd.get("_CFURLString", "").rstrip("/").endswith(os.path.basename(app_path)):
                return  # Already there

        # Build Dock tile entry
        file_url = "file://" + app_path + "/"
        tile = {
            "tile-data": {
                "file-data": {
                    "_CFURLString": file_url,
                    "_CFURLStringType": 15,
                },
                "file-label": os.path.basename(app_path).replace(".app", ""),
                "file-type": 41,
            },
            "tile-type": "file-tile",
        }
        persistent.append(tile)
        dock["persistent-apps"] = persistent

        with open(dock_plist, "wb") as f:
            plistlib.dump(dock, f)

        # Restart Dock to pick up the change
        subprocess.run(["killall", "Dock"], capture_output=True)
    except Exception as e:
        print(f"  ⚠ Could not add to Dock: {e}")
